# Generated by Django 2.0.3 on 2018-04-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(max_length=102400, verbose_name='body of article')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='the create time of article')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name="the article's last modified time")),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='commit time of comment')),
                ('comment_content', models.CharField(max_length=255, unique=True)),
                ('commit_nickname', models.CharField(max_length=64)),
                ('commit_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('isactive', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jared.User', to_field='username'),
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Jared.Comment', to_field='comment_content'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='Jared.Tag'),
        ),
    ]
