# Generated by Django 2.0.3 on 2018-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jared', '0002_auto_20180509_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='access_times',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
